import Nav from '@/components/Nav';
import SessionProvider from '../components/SessionProvider'
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <main className="fsection-main">
            <Nav />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
